# -- This script was generated by a beta version of the ERD tool in pgAdmin 4.
# -- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
# BEGIN;
#
#
# CREATE TABLE IF NOT EXISTS public.department
# (
#     id bigint NOT NULL DEFAULT nextval('department_id_seq'::regclass),
#     description character varying(255) COLLATE pg_catalog."default",
#     name character varying(255) COLLATE pg_catalog."default",
#     directorate_id bigint,
#     CONSTRAINT department_pkey PRIMARY KEY (id)
# );
#
# CREATE TABLE IF NOT EXISTS public.directorate
# (
#     id bigint NOT NULL DEFAULT nextval('directorate_id_seq'::regclass),
#     description character varying(255) COLLATE pg_catalog."default",
#     name character varying(255) COLLATE pg_catalog."default",
#     director_id bigint,
#     CONSTRAINT directorate_pkey PRIMARY KEY (id)
# );
#
# CREATE TABLE IF NOT EXISTS public.employee
# (
#     id bigint NOT NULL DEFAULT nextval('employee_id_seq'::regclass),
#     age integer,
#     family_name character varying(255) COLLATE pg_catalog."default",
#     first_name character varying(255) COLLATE pg_catalog."default",
#     password character varying(255) COLLATE pg_catalog."default",
#     pin character varying(255) COLLATE pg_catalog."default",
#     "position" character varying(255) COLLATE pg_catalog."default",
#     username character varying(255) COLLATE pg_catalog."default",
#     departament_id bigint,
#     directorate_id bigint,
#     CONSTRAINT employee_pkey PRIMARY KEY (id)
# );
#
# CREATE TABLE IF NOT EXISTS public.employees_roles
# (
#     employee_id bigint NOT NULL,
#     role_id bigint NOT NULL,
#     CONSTRAINT employees_roles_pkey PRIMARY KEY (employee_id, role_id)
# );
#
# CREATE TABLE IF NOT EXISTS public.roles
# (
#     id bigint NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
#     role_description character varying(255) COLLATE pg_catalog."default",
#     role_name character varying(255) COLLATE pg_catalog."default",
#     CONSTRAINT roles_pkey PRIMARY KEY (id)
# );
#
# ALTER TABLE IF EXISTS public.department
#     ADD CONSTRAINT fk7gng9m0kx8a5pb65ox8h006jf FOREIGN KEY (directorate_id)
#     REFERENCES public.directorate (id) MATCH SIMPLE
#     ON UPDATE NO ACTION
#        ON DELETE NO ACTION;
#
#
# ALTER TABLE IF EXISTS public.directorate
#     ADD CONSTRAINT fkn6ngn66ewfsqylw56oyh3ybuh FOREIGN KEY (director_id)
#     REFERENCES public.employee (id) MATCH SIMPLE
#     ON UPDATE NO ACTION
#        ON DELETE NO ACTION;
#
#
# ALTER TABLE IF EXISTS public.employee
#     ADD CONSTRAINT fkqf56vr9t9qpai4ciqqh34qkyo FOREIGN KEY (directorate_id)
#     REFERENCES public.directorate (id) MATCH SIMPLE
#     ON UPDATE NO ACTION
#        ON DELETE NO ACTION;
#
#
# ALTER TABLE IF EXISTS public.employee
#     ADD CONSTRAINT fktfms97gd3sl679htvn6qtekpq FOREIGN KEY (departament_id)
#     REFERENCES public.department (id) MATCH SIMPLE
#     ON UPDATE NO ACTION
#        ON DELETE NO ACTION;
#
#
# ALTER TABLE IF EXISTS public.employees_roles
#     ADD CONSTRAINT fk8kbib04ourjps7lcae95gqdj5 FOREIGN KEY (employee_id)
#     REFERENCES public.employee (id) MATCH SIMPLE
#     ON UPDATE NO ACTION
#        ON DELETE NO ACTION;
#
#
# ALTER TABLE IF EXISTS public.employees_roles
#     ADD CONSTRAINT fkhk2e0x3yolbbm1kr84qywb6kb FOREIGN KEY (role_id)
#     REFERENCES public.roles (id) MATCH SIMPLE
#     ON UPDATE NO ACTION
#        ON DELETE NO ACTION;
#
# END;